sudo: false
language: node_js
node_js: "stable"
env:
  - GH_USER_EMAIL="azuciao@gmail.com"
  - GH_USER_NAME="azu"
after_success:
  - |

       $(npm bin)/set-up-ssh --key $encrypted_0713a35a8e5d_key -iv $encrypted_0713a35a8e5d_iv \
                             --path-encrypted-key ".travis/github_deploy_key.enc"

       # Add the SSH-related commands here, see:
       # https://github.com/alrra/travis-scripts/blob/master/doc/github-deploy-keys.md#26-set-up-ssh-connection-for-travis-ci
       $(npm bin)/update-branch --commands "npm run build" \
                               --commit-message "Update gh-pages [skip ci]" \
                               --directory "public" \
                               --distribution-branch "gh-pages" \
                               --source-branch "master"